Add prettier
saleor/saleor-cli pull request #163
Opened 2022-06-24 16:05 UTC by timuric

Run prettier on commit

2022-06-25 16:17 UTC, zaiste requested changes

2022-06-25 16:17 UTC, zaiste commented on README.md
> +Before installing packages run typescript compiler:
@timuric This is incorrect. TypeScript is a dev dependency. Why did you add this?

2022-06-27 05:32 UTC, timuric commented on README.md
> +Before installing packages run typescript compiler:
@zaiste Please try to install a fresh clone of the repo

2022-07-04 14:53 UTC, closed without merging

2022-07-04 14:55 UTC, zaiste commented on README.md
> +Before installing packages run typescript compiler:
@timuric I see it. Good catch, but this must be solved differently