Make `app deploy` to wait till deployment finishes
saleor/saleor-cli pull request #212
Opened 2022-07-28 12:25 UTC by zaiste

Also enabled the `CI` environment variable along with the `--dispatch` option to skip the deployment await.

Improved and refined the command output.

2022-07-28 12:30 UTC, lkostrowski commented
First look at these box-sections - awesome!!

2022-07-28 12:43 UTC, lkostrowski requested changes

2022-07-28 12:43 UTC, lkostrowski commented on src/cli/app/deploy.ts
> +  _.option('dispatch', {
Maybe I'm not familiar with "dispatch" term in this context, so without reading description, I wouldn't firgure out what dispatch is. 
Is this term some pattern used in other apps? Will it be understandable for community?

2022-07-28 12:43 UTC, lkostrowski commented on src/cli/app/deploy.ts
> +  if (!!process.env.CI || !argv.dispatch) {
I think it's good idea to have both ways. In many environments CI will be inferred by default and users will not have to remember about `dispatch` 👍

2022-07-28 12:43 UTC, lkostrowski commented on src/cli/app/deploy.ts
> +  if (!!process.env.CI || !argv.dispatch) {
Nitpick/suggestion - maybe I'd extract some util like `shouldWaitUntilDeployed = () => (!!process.env.CI || !argv.dispatch)` to add some semantics

2022-07-28 12:43 UTC, lkostrowski commented on src/cli/app/deploy.ts
> +    console.log('');
Is it needed?

2022-07-28 12:43 UTC, lkostrowski commented on src/lib/vercel.ts
> +
Probably we shouldn't keep dead code?

2022-07-28 12:43 UTC, lkostrowski commented on src/lib/vercel.ts
> +  async getDeployment(deploymentId: string): Promise<any> {
`Promise<any>` isn't type safe. If you perform runtime-check what is returned (which is good), it should be `Promise<unknown>`

2022-07-28 12:43 UTC, lkostrowski commented on src/lib/vercel.ts
> +      readyState = rs;
can we avoid mutation?

2022-07-28 14:12 UTC, zaiste commented on src/cli/app/deploy.ts
> +  _.option('dispatch', {
We can change this. Intuitively I used a term from the queueing nomenclature i.e. putting a long-running job on an execution queue is usually called _dispatching_; in other words we don't wait for the result, the execution is started and run asynchronously.

2022-07-28 14:14 UTC, zaiste commented on src/cli/app/deploy.ts
> +    console.log('');
It's easier to see newlines this way when composing messages. With the `\n` at the end it's a bit difficult to see. I don't have a strong preference here. It's just slightly more practical.

2022-07-28 14:59 UTC, zaiste commented on src/cli/app/deploy.ts
> +  if (!!process.env.CI || !argv.dispatch) {
Yes, good idea

2022-07-28 15:04 UTC, zaiste commented
@lkostrowski PR refined. WDYT?

2022-07-29 06:42 UTC, lkostrowski approved these changes
LGTM 👏

2022-07-29 06:42 UTC, lkostrowski commented on src/cli/app/deploy.ts
> +  _.option('dispatch', {
That sounds good 👍 

If we have a "better name" later (maybe more known for frontend devs) we can always add alias

2022-07-29 06:42 UTC, lkostrowski commented on src/cli/app/deploy.ts
> +    console.log('');
How about 

```
console.log('\n');
```

It's a nitpick but this way it's pretty obvious what it does. But up2u

2022-07-29 10:17 UTC, 2can approved these changes

2022-07-29 15:29 UTC, merged

2022-07-29 16:12 UTC, zaiste commented on src/cli/app/deploy.ts
> +    console.log('');
Nitpicks are always welcome. Here, that would be a **double** newline, but let's discuss it on Monday. We have some ideas for a global approach.

2022-07-29 16:46 UTC, lkostrowski commented on src/cli/app/deploy.ts
> +    console.log('');
Ach, ok, I'm not used to CLI too much, was using mainly Ink for that. Its fine

2022-08-03 11:33 UTC, michalina-graczyk commented
![image](https://user-images.githubusercontent.com/25908728/182597924-8aa6bc3f-cf28-4952-a8bf-f2fd33208ed3.png)
@zaiste There is still an `undefined` in the Dashboard URL