Verify environment presence in the useEnvironment middleware
saleor/saleor-cli pull request #217
Opened 2022-07-29 13:04 UTC by 2can

- Move verification logic from `env remove` to useEnvironment middleware
- Allow to pass environment option/positional by name
- Introduce spinner for better UX
- Show custom error message for missing env

2022-07-29 13:31 UTC, lkostrowski requested changes

2022-07-29 13:31 UTC, lkostrowski commented on src/cli/env/remove.ts
> +    })) as any;
Please avoid `any` casting. It basically disables typescript.

I suggest `as unknown` and prepare a type narrowing check - something like `typeof result === 'object' && 'task_id' in result`

2022-07-29 13:31 UTC, lkostrowski commented on src/middleware/index.ts
> +  }
This block has quite high complexity. It introduces `any` and nests both errors and conditionals.

Could you refactor it, maybe extracting some methods?

2022-07-29 13:31 UTC, lkostrowski commented on src/middleware/index.ts
> +  let env;
`let env` is hidden `any` type. We should avoid that

2022-07-29 16:28 UTC, zaiste approved these changes

2022-07-29 16:30 UTC, merged

2022-08-01 09:27 UTC, lkostrowski commented
@michalina-graczyk can you please test it?