Make an experimental single file build for the CLI
saleor/saleor-cli pull request #253
Opened 2022-08-05 12:26 UTC by zaiste

Fixes #221

2022-08-05 15:38 UTC, 2can reviewed
@zaiste the only error I've found is for `info` command

`ERROR ENOENT: no such file or directory, open '/Users/tukan/Workspace/saleor/saleor-cli/fonts/Standard.flf'`

2022-08-08 06:52 UTC, lkostrowski commented
Please wait with this, I don't want to introduce any instability when we don't have tests.

2022-08-09 14:24 UTC, zaiste commented
@lkostrowski we can try to release it **only** as RC, and then revert if needed WDYT?

2022-08-10 09:10 UTC, lkostrowski requested changes
I checked locally and it's great that CLI is <10mb. It seems that we don't need a binary and proper compilation is enough

However:
1. Let's support at least Node 16 (like before), but I hope we can include 14x too
2. Ensure no *behavior* change is introduced. This is a compilation so we can't merge any code that was commented out here.
3. We need to run QA test and ensure everything works. This change is simple, but swapping compiler can alter things we don't see. I'd like @michalina-graczyk to test it on branch and confirm there are no regressions

@michalina-graczyk to build it:
1. Clone repo and move to `make-esbuild` branch
2. Run `pnpm build` 
3. Run CLI as `node ./dist/saleor.js CMD`

2022-08-10 09:10 UTC, lkostrowski commented on package.json
> +    "bundle": "esbuild src/cli.ts --bundle --minify --outfile=dist/saleor.js --platform=node --format=esm --target=node18 --banner:js=\"import { createRequire } from 'module';const require = createRe
`--target=node18` I'd like to support at least node 16, but let's try with node 14 too. AFAIK we only need to polyfill or drop replaceAll api

2022-08-10 09:10 UTC, lkostrowski commented on src/cli.ts
> +// notifier.notify({ isGlobal: true });
Why this is left like this?

2022-08-17 09:03 UTC, michalina-graczyk commented
I have checked that. This is a list of my results:
- [x]  login
- [ ]  info

```jsx
saleor-cli git:(make-esbuild) ✗ node ./dist/saleor.js info

                                               ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
                                            ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
                ▄█████████████████████████████████████████▀░░░░░░░░░░░░░░░░
             ▄███▀                 ░░░░░░░░░░░░░░░ ▄███▀░░░░░░░░░░░░░░░
          ▄███▀                ░░░░░░░░░░░░░░░░░▄███▀░░░░░░░░░░░░░░
       ▄███▀               ░░░░░░░░░░░░░░░░░░▄███▀░░░░░░░░░░░░
    ▄███▀                                 ▄███▀
 ▄█████████████████████████████████████████▀         Saleor Commerce CLI v1.12.0

 ERROR ENOENT: no such file or directory, open '/Users/michalinqa/Desktop/projekty/CLI-253/saleor-cli/fonts/Standard.flf'
```

- [x]  node ./dist/saleor.js env create
- [x]  check if env is present on dasboard (check in graphical UI)
- [ ]  Deploy our react-storefront starter pack to Vercel

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/03ecfcea-c7ed-4e0c-844d-8d9623a4b3b1/Untitled.png)

- [ ]  create store front (saleor storefront create)

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/b1bd189f-8c86-4ee8-bac7-36cd84248465/Untitled.png)

- [ ]  check if dir with storefront project was created under selected name (or defalut if no name was picked "saleor-demo")
- [x]  check data in configuration file (.env in storefront folder, looking for NEXT_PUBLIC_API_URI) is connected to selected environment
- [x]  check if storefront is launched on listed port
- [ ]  execute "saleor storefront create --demo”

same result as stf create

- [ ]  check if demo project was created
- [ ]  check if demo is launched on listed port
- [x]  remove env (saleor env remove [key to env])
- [x]  logout
- [ ]  app create

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/d211596d-4d75-48d9-84c9-e6068b63d2d4/Untitled.png)

- [ ]  vercel login

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/03e7773b-45f3-472c-adcb-99207f14b3fe/Untitled.png)

- [ ]  saleor app deploy on vercel

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/7ea3f0f2-bf66-47fb-8f3a-7010b594d86a/Untitled.png)

2022-09-14 12:19 UTC, zaiste commented on package.json
> +    "bundle": "esbuild src/cli.ts --bundle --minify --outfile=dist/saleor.js --platform=node --format=esm --target=node18 --banner:js=\"import { createRequire } from 'module';const require = createRe
Done

2022-09-14 12:19 UTC, zaiste commented on src/cli.ts
> +// notifier.notify({ isGlobal: true });
Fixed

2022-09-14 12:20 UTC, zaiste commented
@michalina-graczyk @2can could you re-do your tests? it should work now

2022-09-14 12:21 UTC, lkostrowski approved these changes
Lets merge and branch v1.15 already

@michalina-graczyk please test on v1.15rc1 (diversely)

2022-09-14 12:27 UTC, mmiszy commented on package.json
> -    "build",
Shouldn't there be `dist` instead?

2022-09-14 12:27 UTC, mmiszy commented on src/cli/info.ts
> +import packageJson from '../../package.json';
I haven't tested it, but does it work right now? Shouldn't it be:
```suggestion
import packageJson from '../../package.json' assert { type: 'json' };
```

2022-09-14 12:28 UTC, zaiste commented on src/cli/info.ts
> +import packageJson from '../../package.json';
@mmiszy you're too quick! :) before you commented there's a new commit to disable it

2022-09-14 12:28 UTC, zaiste commented on package.json
> -    "build",
@mmiszy yes, good catch

2022-09-14 12:52 UTC, merged