Align `storefront create` with react-storefront turborepo
saleor/saleor-cli pull request #254
Opened 2022-08-05 12:38 UTC by 2can

2022-08-05 14:13 UTC, lkostrowski approved these changes

2022-08-05 14:24 UTC, lkostrowski requested changes
Tested locally. Server on :3000 starts, but it fails running 

```
storefront:dev: Module not found: Can't resolve '@saleor/ui-kit'
storefront:dev: > 1 | import { ChipButton } from "@saleor/ui-kit";
storefront:dev:   2 | import React from "react";
storefront:dev:   3 | 
storefront:dev:   4 | import { Box } from "../Box";
storefront:dev: 
```

2022-08-05 15:10 UTC, 2can commented
@lkostrowski `ui-kit` build step added

2022-08-08 06:44 UTC, lkostrowski commented on src/cli/storefront/create.ts
> +    ['dev', '--filter=storefront'],
@mmiszy correct me if I'm wrong, but AFAIK turbo can/should be configured with proper deps. So if we run storefront, ui-kit should build automatically and listen to changes.

Also, this is detail of storefront app. I don't think we should replicate internal scripts structure in CLI. This is fragile and CLI will break each time some of these scripts change.

I hope we can run single Storefront script and Storefront can handle it's start.

(ps I don't know why do we start it, IMO it's only to press ctrl+c)

2022-08-08 06:46 UTC, lkostrowski commented
Confirmed locally, storefront starts

2022-08-08 06:49 UTC, mmiszy commented on src/cli/storefront/create.ts
> +  await run('pnpm', ['build', '--filter=ui-kit'], { cwd: process.cwd() });
```suggestion
  await run('pnpm', ['build', '--filter=storefront^...'], { cwd: process.cwd() });
```

2022-08-08 06:49 UTC, mmiszy commented on src/cli/storefront/create.ts
> +    ['dev', '--filter=storefront'],
> AFAIK turbo can/should be configured with proper deps. So if we run storefront, ui-kit should build automatically and listen to changes.

Yes, I've added a comment above
https://github.com/saleor/saleor-cli/pull/254/files#r939877484

2022-08-08 06:52 UTC, mmiszy requested changes
Let's change `--filter=ui-kit` to `--filter=storefront^...` so that it's more loosely coupled with the internal structure of the storefront and more futureproof.

2022-08-08 06:52 UTC, mmiszy commented on src/cli/storefront/create.ts
> +  await run('pnpm', ['build', '--filter=ui-kit'], { cwd: process.cwd() });
Rel: https://turborepo.org/docs/core-concepts/filtering#include-dependencies-of-matched-packages

2022-08-08 06:54 UTC, lkostrowski commented on src/cli/storefront/create.ts
> +  await run('pnpm', ['build', '--filter=ui-kit'], { cwd: process.cwd() });
@mmiszy do we need to build storefront? Last cmd is `dev` so maybe just `pnpm run dev --filter=storefront^...`?

2022-08-08 06:55 UTC, mmiszy commented on src/cli/storefront/create.ts
> +  await run('pnpm', ['build', '--filter=ui-kit'], { cwd: process.cwd() });
How is that different from what I suggested @lkostrowski ?

2022-08-08 06:56 UTC, mmiszy commented on src/cli/storefront/create.ts
> +  await run('pnpm', ['build', '--filter=ui-kit'], { cwd: process.cwd() });
We need to build storefront's dependencies. We're not building storefront here.

2022-08-08 06:58 UTC, lkostrowski commented on src/cli/storefront/create.ts
> +  await run('pnpm', ['build', '--filter=ui-kit'], { cwd: process.cwd() });
I was thinking about `storefront dev` triggering `ui-kit dev`, so when I edit ui-kit in dev mode, it gets automatically updated in the tree. And `storefront dev` can (in turbo config) mark that `ui-kit build` must happen before (hence no need to write this explicitely). At least thats how I was configuring turbo before

2022-08-08 07:00 UTC, mmiszy commented on src/cli/storefront/create.ts
> +  await run('pnpm', ['build', '--filter=ui-kit'], { cwd: process.cwd() });
If we want to start the `dev` script for storefront and its dependencies we need to run `pnpm dev --filter=storefront...`

2022-08-08 07:04 UTC, lkostrowski commented on src/cli/storefront/create.ts
> +  await run('pnpm', ['build', '--filter=ui-kit'], { cwd: process.cwd() });
Yup and this is probably something we should do @2can @zaiste

2022-08-08 07:22 UTC, lkostrowski approved these changes
Tested locally, works

2022-08-08 07:40 UTC, mmiszy approved these changes

2022-08-08 09:26 UTC, zaiste approved these changes

2022-08-08 09:26 UTC, merged