Parametrize the URLs used for apps register flow
saleor/saleor-cli pull request #268
Opened 2022-08-11 09:12 UTC by zaiste

2022-08-11 12:16 UTC, lkostrowski requested changes

2022-08-11 12:16 UTC, lkostrowski commented on src/cli/app/deploy.ts
> +      default: 'https://appraptor.deno.dev/encrypt',
@zaiste please migrate to vercel

2022-08-11 12:16 UTC, lkostrowski commented on src/lib/vercel.ts
> +
Please remove dead code

2022-08-22 12:11 UTC, 2can approved these changes

2022-08-22 12:12 UTC, merged