Allow single command deployment of storefront with checkout
saleor/saleor-cli pull request #290
Opened 2022-08-25 09:08 UTC by 2can

2022-08-29 08:45 UTC, lkostrowski requested changes

2022-08-29 08:45 UTC, lkostrowski commented on src/cli/checkout/deploy.ts
> +) => {
Please avoid that many arguments, it's not nice API, easy to make a mistake (3 strings in the row) etc.

This can be an object destructuring

2022-08-29 08:45 UTC, lkostrowski commented on src/cli/checkout/deploy.ts
> +  // SETUP CHECKOUT APP
Let's avoid comments like this. Code can be self-explaining if blocks are extracted to functions, each functions adds level of detail

2022-08-29 08:45 UTC, lkostrowski commented on src/cli/checkout/deploy.ts
> +  );
We should probably .catch or try/catch early, log error if it fails

2022-08-29 08:45 UTC, lkostrowski commented on src/cli/checkout/deploy.ts
> +  const { alias } = await vercel.getDeployment(checkoutAppDeploymentId);
Response from external system should be always validated. `alias` field can be missing. Let's check it's existence and fail early with proper message

2022-08-29 08:45 UTC, lkostrowski commented on src/cli/checkout/deploy.ts
> +export const setupCheckout = async (
why there are methods `setupAppCheckout` and `setupCheckout`?

2022-08-29 08:45 UTC, lkostrowski commented on src/cli/storefront/create.ts
> +      desc: 'specify checkout deployment',
@timuric please confirm - should `storefront create` add checkout deployment by default?

2022-09-12 08:35 UTC, closed without merging

2022-09-13 07:49 UTC, 2can commented
Closed in favour of https://github.com/saleor/saleor-cli/pull/346