Distinguish between Regular & RC releases
saleor/saleor-cli pull request #302
Opened 2022-08-29 09:23 UTC by zaiste

2022-08-29 13:48 UTC, lkostrowski requested changes

2022-08-29 13:48 UTC, lkostrowski commented on .github/workflows/release.yml
> +        if: inputs.version != 'rc'
where does inputs.version come from?

2022-08-29 13:48 UTC, lkostrowski commented on .github/workflows/release.yml
>          run: pnpm release ${{ inputs.version }} --ci --dry-run
I'd like regular release to open a draft release in github.

After release is published, action should react on that and release to npm

This should be a separate work flow, so I can choose between these 2 options:
- Publish RC to npm
- Open draft PR in Github

2022-08-30 10:00 UTC, zaiste commented on .github/workflows/release.yml
> +        if: inputs.version != 'rc'
@lkostrowski from the `inputs` section above

2022-08-30 15:33 UTC, merged