Extract env graphql endpoint logic to separate fn
saleor/saleor-cli pull request #306
Opened 2022-08-29 15:35 UTC by 2can

2022-08-30 05:40 UTC, lkostrowski requested changes
Please consider https://github.com/saleor/saleor-cli/issues/277

Soon there will be required support for local Saleor domain, so user can set `localhost:1234/graphql` as Saleor endpoint

2022-08-30 05:40 UTC, lkostrowski commented on src/lib/environment.test.ts
> +);
Log is probably redundant

2022-08-30 05:40 UTC, lkostrowski commented on src/lib/environment.test.ts
> +  it('returns the environment graphql endpoint', async () => {
Test suits are not descriptive. They should be a "documentation", so by reading a test I should be able to understand what is the behaviour for given conditions

This is very specific here - it fetches response from API based on provided arguments

2022-08-31 08:42 UTC, zaiste approved these changes

2022-08-31 08:42 UTC, merged