Add PR template
saleor/saleor-cli pull request #307
Opened 2022-08-30 05:26 UTC by lkostrowski

2022-08-30 06:46 UTC, peelar commented
What do you think about reusing [the templates in `saleor/saleor`](https://github.com/saleor/saleor/tree/main/.github/ISSUE_TEMPLATE)?

2022-08-30 07:00 UTC, lkostrowski commented
@peelar I think its PR template https://github.com/saleor/saleor/blob/main/.github/PULL_REQUEST_TEMPLATE.md

But it's specific for Saleor/Saleor backend logic

2022-08-30 08:03 UTC, peelar commented
Ah sorry, wrong link. What I meant is that I think we should try to introduce a common structure to the PR/issue templates in our main repositories.

2022-08-30 08:08 UTC, lkostrowski commented
@peelar I agree in general but I don't think we can achieve it at the moment. There are not only very different types (lib vs app vs cli, client vs internal, frontend vs backend), but also very different maturity level. Points from other repositories might not really be valid here. We also don't have established our final DoD so it's incremental

2022-08-30 08:59 UTC, peelar approved these changes

2022-08-30 08:59 UTC, peelar commented on .github/PULL_REQUEST_TEMPLATE.md
> +**I want to merge this PR, because: ***
```suggestion
**I want to merge this PR because: ***
```

2022-08-30 09:34 UTC, krzysztofwolski requested changes
From my experience, markdown templates are mostly filled improperly (not everyone knows how to use markdown checkboxes for example).

I would suggest using YAML form templates https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

Experience of using them is much better and a chance to use the wrong syntax is minimized

2022-08-30 09:43 UTC, lkostrowski commented
@krzysztofwolski this is great but it's only supported for issues :/

2022-08-30 09:48 UTC, krzysztofwolski approved these changes
Hope YAML templates will land on PRs in the future :c

2022-08-30 09:59 UTC, lkostrowski commented
@krzysztofwolski afaik it's on the roadmap, we will introduce it as soon as its shipped ;)

2022-08-30 09:59 UTC, merged

2022-08-31 07:33 UTC, michalina-graczyk commented
Not need to be in QA.