Docs
saleor/saleor-cli pull request #326
Opened 2022-09-06 09:26 UTC by 2can

**I want to merge this PR because: ***
It creates docs directory with all commands usage

## Related issues

- https://github.com/saleor/saleor-cli/issues/283 

## Steps to test feature

- 

## I have:

- [x] Tested it locally and it doesn't break existing features
- [x] Added documentation if public changes are introduced
- [ ] Added tests for my code

2022-09-06 09:31 UTC, zaiste approved these changes

2022-09-06 11:16 UTC, lkostrowski requested changes
Please use batch mode examples only for interactive commands that can be made non-interactive.
TBH we can make one section, that explains all "flags" can be passed in single command, we don't have to repeat it

@peelar what do you think?

2022-09-06 11:16 UTC, lkostrowski commented on docs/app.md
> +## saleor app
Lets name file to something like `saleor-app-command`, so its clear when docs are about commands

2022-09-06 11:16 UTC, lkostrowski commented on docs/app.md
> +```
How this is useful?

2022-09-06 11:16 UTC, lkostrowski commented on docs/app.md
> +```
If command is non-interactive, example doesnt make sense. I'd remove it

2022-09-06 11:16 UTC, lkostrowski commented on docs/app.md
> +```
IMO This is not example of batch, because tunnel is not asking interactively about port.

2022-09-06 12:08 UTC, peelar commented on docs/app.md
> +Example usage in batch mode
What does "batch mode" mean? With several options? If so, I would change the wording here or even remove it.

2022-09-07 08:56 UTC, zaiste commented on docs/app.md
> +Example usage in batch mode
@peelar *batch mode* means that arguments are passed from the invocation, and not interactively

2022-09-12 09:13 UTC, 2can commented on docs/app.md
> +```
removed

2022-09-12 09:14 UTC, 2can commented on docs/app.md
> +```
removed

2022-09-12 09:14 UTC, 2can commented on docs/app.md
> +```
removed

2022-09-12 09:14 UTC, 2can commented on docs/app.md
> +## saleor app
updated

2022-09-12 13:19 UTC, 2can commented on docs/app.md
> +Example usage in batch mode
@peelar is it OK? Do you think it should be re-phrased?

2022-09-13 06:47 UTC, lkostrowski requested changes

2022-09-13 06:47 UTC, lkostrowski commented on docs/app.md
> +```
Why do you leave this TODO?

2022-09-13 06:47 UTC, lkostrowski commented on docs/backup.md
> + saleor backup list [key|environment]  List backups of the environment
fix indent

2022-09-13 06:49 UTC, lkostrowski commented on docs/app.md
> +Example usage in batch mode
@2can @peelar lets have a section in `readme.md` `# Batch Mode (non-interactive)` that will explain in few words that commands can be run interactive and non-interactive (batch mode), when batch is good (programmatic usage) and maybe link to some Wikipedia or something

2022-09-13 09:36 UTC, 2can commented on docs/app.md
> +Example usage in batch mode
OK, so let's use "non-interactive"  instead of "batch"

2022-09-13 09:46 UTC, 2can commented on docs/app.md
> +```
Removed. Created issue for that https://github.com/saleor/saleor-cli/issues/352

2022-09-13 11:42 UTC, lkostrowski approved these changes

2022-09-13 11:53 UTC, merged