`saleor login` should give additional info
saleor/saleor-cli pull request #354
Opened 2022-09-13 11:04 UTC by Cloud11PL

**I want to merge this PR because: ***

## Related issues

- 

## Steps to test feature

- 

## I have:

- [ ] Tested it locally and it doesn't break existing features
- [ ] Added documentation if public changes are introduced
- [ ] Added tests for my code

2022-09-13 12:53 UTC, lkostrowski requested changes

2022-09-13 12:53 UTC, lkostrowski commented on src/cli/info.ts
> +    const user = (await GET(API.User, { token })) as any;
Please don't use `any`. You can do `as unknown`, then check if `user.email` exist. If API for some reason changes, `user.email` will crash application

2022-09-14 06:51 UTC, Cloud11PL commented on src/cli/info.ts
> +    const user = (await GET(API.User, { token })) as any;
I based it on other usages of `GET(API...)` in cli, all of them cast it to `any`. I added a check func here

2022-09-14 06:56 UTC, lkostrowski approved these changes

2022-09-14 06:57 UTC, lkostrowski commented on src/cli/info.ts
> +    }
@zaiste here in else we can report error to sentry, so we immediately know something broke

2022-09-19 15:55 UTC, zaiste commented
@Cloud11PL can you rebase?

2022-09-22 09:15 UTC, zaiste approved these changes

2022-09-22 09:15 UTC, merged