Change '/register' to '/signup'
saleor/saleor-cli pull request #355
Opened 2022-09-14 07:29 UTC by Cloud11PL

**I want to merge this PR because: ***

## Related issues

- https://github.com/saleor/saleor-cli/issues/349

## Steps to test feature

- 

## I have:

- [x] Tested it locally and it doesn't break existing features
- [ ] Added documentation if public changes are introduced
- [ ] Added tests for my code

2022-09-14 07:31 UTC, lkostrowski approved these changes

2022-09-14 09:57 UTC, krzysztofwolski approved these changes

2022-09-15 09:00 UTC, zaiste requested changes

2022-09-15 09:00 UTC, zaiste commented on src/cli.ts
> +  .command({
@Cloud11PL for consistency, could you define the alias as on the line 87?

2022-09-15 09:04 UTC, Cloud11PL commented on src/cli.ts
> +  .command({
@zaiste handlers for `organization` or `environment` are created differently than for register. That's why I wrote it this way. Should I completely change the handler for `register`?

2022-09-19 14:42 UTC, zaiste approved these changes

2022-09-19 14:42 UTC, merged

2022-09-20 09:28 UTC, michalina-graczyk commented
![image](https://user-images.githubusercontent.com/25908728/191221790-8a34c3fb-992f-4289-9bb2-37681c538116.png)
it should redirects me to https://cloud.saleor.io/signup 
v.v1.15.0-rc.4