Handle telemetry errors
saleor/saleor-cli pull request #502
Opened 2022-11-02 12:51 UTC by 2can

## I want to merge this PR because 

- It uses a promise-based catch to handle telemetry rejections.

## Related (issues, PRs, topics)

- 

## Steps to test feature

- 

## I have:

- [ ] Tested it locally and it doesn't break existing features
- [ ] Added documentation if public changes are introduced
- [ ] Added tests for my code

2022-11-02 14:29 UTC, lkostrowski approved these changes

2022-11-03 12:20 UTC, zaiste requested changes

2022-11-03 12:20 UTC, zaiste commented on src/middleware/index.ts
> -      got.post(Configuration.TelemetryDomain, {
@2can let's leave the `try/catch` - this just needs an `await`

2022-11-03 12:23 UTC, lkostrowski commented on src/middleware/index.ts
> -      got.post(Configuration.TelemetryDomain, {
await will block thread, while promise + catch should be dispatched and forgotten, right?

2022-11-03 12:27 UTC, 2can commented on src/middleware/index.ts
> -      got.post(Configuration.TelemetryDomain, {
@zaiste my impression was that it was meant to be non-blocking so the process continues with the command

2022-11-03 12:32 UTC, zaiste commented on src/middleware/index.ts
> -      got.post(Configuration.TelemetryDomain, {
`catch()` internally calls `then()`

2022-11-03 12:39 UTC, lkostrowski commented on src/middleware/index.ts
> -      got.post(Configuration.TelemetryDomain, {
But this middleware doesnt wait for this `post` so its non blocking

2022-11-03 12:47 UTC, zaiste commented on src/middleware/index.ts
> -      got.post(Configuration.TelemetryDomain, {
Let's add `uncaughtException` for this case

2022-11-03 12:55 UTC, lkostrowski commented on src/middleware/index.ts
> -      got.post(Configuration.TelemetryDomain, {
I dont understand. It should be caught locally. If its not awaited, it will be caught/resolved asynchronously, without blocking middleware to execute. Try/catch will block. 

I think original solution from @2can is good, or I don't understand something :D

2022-11-03 13:06 UTC, zaiste approved these changes

2022-11-03 13:06 UTC, merged